server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  
logging:
  level:
    root: INFO
info:
  app:
    name: "bach-cloud-ms-simple-consumer-movie"
    encoding: "UTF-8"
    java:
      source: "1.8.0_131"
      target: "1.8.0_131"
user:
  userServiceUrl: http://localhost:8000/