package com.bach.monitor.domain;

public class BachAlarmType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_alarm_type.alarm_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String alarmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_alarm_type.alarm_type_desc
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String alarmTypeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_alarm_type.alarm_type
     *
     * @return the value of bach_alarm_type.alarm_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_alarm_type.alarm_type
     *
     * @param alarmType the value for bach_alarm_type.alarm_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType == null ? null : alarmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_alarm_type.alarm_type_desc
     *
     * @return the value of bach_alarm_type.alarm_type_desc
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getAlarmTypeDesc() {
        return alarmTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_alarm_type.alarm_type_desc
     *
     * @param alarmTypeDesc the value for bach_alarm_type.alarm_type_desc
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setAlarmTypeDesc(String alarmTypeDesc) {
        this.alarmTypeDesc = alarmTypeDesc == null ? null : alarmTypeDesc.trim();
    }
}