package com.bach.monitor.domain;

import java.util.Date;

public class BachDatastageRowsCfg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_rows_cfg.job_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_rows_cfg.logsum
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Integer logsum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_rows_cfg.is_valid
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_rows_cfg.run_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Integer runStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_rows_cfg.start_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_rows_cfg.end_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_rows_cfg.match_cnt
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Integer matchCnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_rows_cfg.job_name
     *
     * @return the value of bach_datastage_rows_cfg.job_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_rows_cfg.job_name
     *
     * @param jobName the value for bach_datastage_rows_cfg.job_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_rows_cfg.logsum
     *
     * @return the value of bach_datastage_rows_cfg.logsum
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Integer getLogsum() {
        return logsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_rows_cfg.logsum
     *
     * @param logsum the value for bach_datastage_rows_cfg.logsum
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setLogsum(Integer logsum) {
        this.logsum = logsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_rows_cfg.is_valid
     *
     * @return the value of bach_datastage_rows_cfg.is_valid
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_rows_cfg.is_valid
     *
     * @param isValid the value for bach_datastage_rows_cfg.is_valid
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_rows_cfg.run_status
     *
     * @return the value of bach_datastage_rows_cfg.run_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Integer getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_rows_cfg.run_status
     *
     * @param runStatus the value for bach_datastage_rows_cfg.run_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setRunStatus(Integer runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_rows_cfg.start_time
     *
     * @return the value of bach_datastage_rows_cfg.start_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_rows_cfg.start_time
     *
     * @param startTime the value for bach_datastage_rows_cfg.start_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_rows_cfg.end_time
     *
     * @return the value of bach_datastage_rows_cfg.end_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_rows_cfg.end_time
     *
     * @param endTime the value for bach_datastage_rows_cfg.end_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_rows_cfg.match_cnt
     *
     * @return the value of bach_datastage_rows_cfg.match_cnt
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Integer getMatchCnt() {
        return matchCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_rows_cfg.match_cnt
     *
     * @param matchCnt the value for bach_datastage_rows_cfg.match_cnt
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setMatchCnt(Integer matchCnt) {
        this.matchCnt = matchCnt;
    }
}