package com.bach.monitor.domain;

public class BachServerUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.ID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.SERVER_ID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.USER_TYPE
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.SERVICE_TYPE
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String serviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.URL
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.USER_NAME
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.PASSWORD
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.CREATOR
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.EDITOR
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_server_user_info.VALID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.ID
     *
     * @return the value of bach_server_user_info.ID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.ID
     *
     * @param id the value for bach_server_user_info.ID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.SERVER_ID
     *
     * @return the value of bach_server_user_info.SERVER_ID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.SERVER_ID
     *
     * @param serverId the value for bach_server_user_info.SERVER_ID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setServerId(String serverId) {
        this.serverId = serverId == null ? null : serverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.USER_TYPE
     *
     * @return the value of bach_server_user_info.USER_TYPE
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.USER_TYPE
     *
     * @param userType the value for bach_server_user_info.USER_TYPE
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.SERVICE_TYPE
     *
     * @return the value of bach_server_user_info.SERVICE_TYPE
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.SERVICE_TYPE
     *
     * @param serviceType the value for bach_server_user_info.SERVICE_TYPE
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType == null ? null : serviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.URL
     *
     * @return the value of bach_server_user_info.URL
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.URL
     *
     * @param url the value for bach_server_user_info.URL
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.USER_NAME
     *
     * @return the value of bach_server_user_info.USER_NAME
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.USER_NAME
     *
     * @param userName the value for bach_server_user_info.USER_NAME
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.PASSWORD
     *
     * @return the value of bach_server_user_info.PASSWORD
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.PASSWORD
     *
     * @param password the value for bach_server_user_info.PASSWORD
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.CREATOR
     *
     * @return the value of bach_server_user_info.CREATOR
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.CREATOR
     *
     * @param creator the value for bach_server_user_info.CREATOR
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.EDITOR
     *
     * @return the value of bach_server_user_info.EDITOR
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.EDITOR
     *
     * @param editor the value for bach_server_user_info.EDITOR
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_server_user_info.VALID
     *
     * @return the value of bach_server_user_info.VALID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_server_user_info.VALID
     *
     * @param valid the value for bach_server_user_info.VALID
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setValid(String valid) {
        this.valid = valid == null ? null : valid.trim();
    }
}