package com.bach.monitor.domain;

import java.util.ArrayList;
import java.util.List;

public class BachDatastageViewInputTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public BachDatastageViewInputTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCollectServerSuffixIsNull() {
            addCriterion("collect_server_suffix is null");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixIsNotNull() {
            addCriterion("collect_server_suffix is not null");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixEqualTo(String value) {
            addCriterion("collect_server_suffix =", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixNotEqualTo(String value) {
            addCriterion("collect_server_suffix <>", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixGreaterThan(String value) {
            addCriterion("collect_server_suffix >", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixGreaterThanOrEqualTo(String value) {
            addCriterion("collect_server_suffix >=", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixLessThan(String value) {
            addCriterion("collect_server_suffix <", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixLessThanOrEqualTo(String value) {
            addCriterion("collect_server_suffix <=", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixLike(String value) {
            addCriterion("collect_server_suffix like", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixNotLike(String value) {
            addCriterion("collect_server_suffix not like", value, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixIn(List<String> values) {
            addCriterion("collect_server_suffix in", values, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixNotIn(List<String> values) {
            addCriterion("collect_server_suffix not in", values, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixBetween(String value1, String value2) {
            addCriterion("collect_server_suffix between", value1, value2, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andCollectServerSuffixNotBetween(String value1, String value2) {
            addCriterion("collect_server_suffix not between", value1, value2, "collectServerSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixIsNull() {
            addCriterion("dboptions_user_suffix is null");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixIsNotNull() {
            addCriterion("dboptions_user_suffix is not null");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixEqualTo(String value) {
            addCriterion("dboptions_user_suffix =", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixNotEqualTo(String value) {
            addCriterion("dboptions_user_suffix <>", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixGreaterThan(String value) {
            addCriterion("dboptions_user_suffix >", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixGreaterThanOrEqualTo(String value) {
            addCriterion("dboptions_user_suffix >=", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixLessThan(String value) {
            addCriterion("dboptions_user_suffix <", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixLessThanOrEqualTo(String value) {
            addCriterion("dboptions_user_suffix <=", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixLike(String value) {
            addCriterion("dboptions_user_suffix like", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixNotLike(String value) {
            addCriterion("dboptions_user_suffix not like", value, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixIn(List<String> values) {
            addCriterion("dboptions_user_suffix in", values, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixNotIn(List<String> values) {
            addCriterion("dboptions_user_suffix not in", values, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixBetween(String value1, String value2) {
            addCriterion("dboptions_user_suffix between", value1, value2, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andDboptionsUserSuffixNotBetween(String value1, String value2) {
            addCriterion("dboptions_user_suffix not between", value1, value2, "dboptionsUserSuffix");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameIsNull() {
            addCriterion("query_table_name is null");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameIsNotNull() {
            addCriterion("query_table_name is not null");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameEqualTo(String value) {
            addCriterion("query_table_name =", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameNotEqualTo(String value) {
            addCriterion("query_table_name <>", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameGreaterThan(String value) {
            addCriterion("query_table_name >", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("query_table_name >=", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameLessThan(String value) {
            addCriterion("query_table_name <", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameLessThanOrEqualTo(String value) {
            addCriterion("query_table_name <=", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameLike(String value) {
            addCriterion("query_table_name like", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameNotLike(String value) {
            addCriterion("query_table_name not like", value, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameIn(List<String> values) {
            addCriterion("query_table_name in", values, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameNotIn(List<String> values) {
            addCriterion("query_table_name not in", values, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameBetween(String value1, String value2) {
            addCriterion("query_table_name between", value1, value2, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andQueryTableNameNotBetween(String value1, String value2) {
            addCriterion("query_table_name not between", value1, value2, "queryTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameIsNull() {
            addCriterion("collection_table_name is null");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameIsNotNull() {
            addCriterion("collection_table_name is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameEqualTo(String value) {
            addCriterion("collection_table_name =", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameNotEqualTo(String value) {
            addCriterion("collection_table_name <>", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameGreaterThan(String value) {
            addCriterion("collection_table_name >", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("collection_table_name >=", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameLessThan(String value) {
            addCriterion("collection_table_name <", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameLessThanOrEqualTo(String value) {
            addCriterion("collection_table_name <=", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameLike(String value) {
            addCriterion("collection_table_name like", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameNotLike(String value) {
            addCriterion("collection_table_name not like", value, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameIn(List<String> values) {
            addCriterion("collection_table_name in", values, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameNotIn(List<String> values) {
            addCriterion("collection_table_name not in", values, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameBetween(String value1, String value2) {
            addCriterion("collection_table_name between", value1, value2, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andCollectionTableNameNotBetween(String value1, String value2) {
            addCriterion("collection_table_name not between", value1, value2, "collectionTableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("table_name is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("table_name is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("table_name =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("table_name <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("table_name >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("table_name >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("table_name <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("table_name <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("table_name like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("table_name not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("table_name in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("table_name not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("table_name between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("table_name not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierIsNull() {
            addCriterion("output_job_identifier is null");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierIsNotNull() {
            addCriterion("output_job_identifier is not null");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierEqualTo(String value) {
            addCriterion("output_job_identifier =", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierNotEqualTo(String value) {
            addCriterion("output_job_identifier <>", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierGreaterThan(String value) {
            addCriterion("output_job_identifier >", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("output_job_identifier >=", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierLessThan(String value) {
            addCriterion("output_job_identifier <", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierLessThanOrEqualTo(String value) {
            addCriterion("output_job_identifier <=", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierLike(String value) {
            addCriterion("output_job_identifier like", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierNotLike(String value) {
            addCriterion("output_job_identifier not like", value, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierIn(List<String> values) {
            addCriterion("output_job_identifier in", values, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierNotIn(List<String> values) {
            addCriterion("output_job_identifier not in", values, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierBetween(String value1, String value2) {
            addCriterion("output_job_identifier between", value1, value2, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputJobIdentifierNotBetween(String value1, String value2) {
            addCriterion("output_job_identifier not between", value1, value2, "outputJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierIsNull() {
            addCriterion("output_record_identifier is null");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierIsNotNull() {
            addCriterion("output_record_identifier is not null");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierEqualTo(String value) {
            addCriterion("output_record_identifier =", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierNotEqualTo(String value) {
            addCriterion("output_record_identifier <>", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierGreaterThan(String value) {
            addCriterion("output_record_identifier >", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("output_record_identifier >=", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierLessThan(String value) {
            addCriterion("output_record_identifier <", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierLessThanOrEqualTo(String value) {
            addCriterion("output_record_identifier <=", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierLike(String value) {
            addCriterion("output_record_identifier like", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierNotLike(String value) {
            addCriterion("output_record_identifier not like", value, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierIn(List<String> values) {
            addCriterion("output_record_identifier in", values, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierNotIn(List<String> values) {
            addCriterion("output_record_identifier not in", values, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierBetween(String value1, String value2) {
            addCriterion("output_record_identifier between", value1, value2, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputRecordIdentifierNotBetween(String value1, String value2) {
            addCriterion("output_record_identifier not between", value1, value2, "outputRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeIsNull() {
            addCriterion("output_update_time is null");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeIsNotNull() {
            addCriterion("output_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeEqualTo(String value) {
            addCriterion("output_update_time =", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeNotEqualTo(String value) {
            addCriterion("output_update_time <>", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeGreaterThan(String value) {
            addCriterion("output_update_time >", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("output_update_time >=", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeLessThan(String value) {
            addCriterion("output_update_time <", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("output_update_time <=", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeLike(String value) {
            addCriterion("output_update_time like", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeNotLike(String value) {
            addCriterion("output_update_time not like", value, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeIn(List<String> values) {
            addCriterion("output_update_time in", values, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeNotIn(List<String> values) {
            addCriterion("output_update_time not in", values, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeBetween(String value1, String value2) {
            addCriterion("output_update_time between", value1, value2, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOutputUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("output_update_time not between", value1, value2, "outputUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierIsNull() {
            addCriterion("stage_job_identifier is null");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierIsNotNull() {
            addCriterion("stage_job_identifier is not null");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierEqualTo(String value) {
            addCriterion("stage_job_identifier =", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierNotEqualTo(String value) {
            addCriterion("stage_job_identifier <>", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierGreaterThan(String value) {
            addCriterion("stage_job_identifier >", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("stage_job_identifier >=", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierLessThan(String value) {
            addCriterion("stage_job_identifier <", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierLessThanOrEqualTo(String value) {
            addCriterion("stage_job_identifier <=", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierLike(String value) {
            addCriterion("stage_job_identifier like", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierNotLike(String value) {
            addCriterion("stage_job_identifier not like", value, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierIn(List<String> values) {
            addCriterion("stage_job_identifier in", values, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierNotIn(List<String> values) {
            addCriterion("stage_job_identifier not in", values, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierBetween(String value1, String value2) {
            addCriterion("stage_job_identifier between", value1, value2, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageJobIdentifierNotBetween(String value1, String value2) {
            addCriterion("stage_job_identifier not between", value1, value2, "stageJobIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierIsNull() {
            addCriterion("bstage_record_identifier is null");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierIsNotNull() {
            addCriterion("bstage_record_identifier is not null");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierEqualTo(String value) {
            addCriterion("bstage_record_identifier =", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierNotEqualTo(String value) {
            addCriterion("bstage_record_identifier <>", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierGreaterThan(String value) {
            addCriterion("bstage_record_identifier >", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("bstage_record_identifier >=", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierLessThan(String value) {
            addCriterion("bstage_record_identifier <", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierLessThanOrEqualTo(String value) {
            addCriterion("bstage_record_identifier <=", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierLike(String value) {
            addCriterion("bstage_record_identifier like", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierNotLike(String value) {
            addCriterion("bstage_record_identifier not like", value, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierIn(List<String> values) {
            addCriterion("bstage_record_identifier in", values, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierNotIn(List<String> values) {
            addCriterion("bstage_record_identifier not in", values, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierBetween(String value1, String value2) {
            addCriterion("bstage_record_identifier between", value1, value2, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andBstageRecordIdentifierNotBetween(String value1, String value2) {
            addCriterion("bstage_record_identifier not between", value1, value2, "bstageRecordIdentifier");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeIsNull() {
            addCriterion("stage_update_time is null");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeIsNotNull() {
            addCriterion("stage_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeEqualTo(String value) {
            addCriterion("stage_update_time =", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeNotEqualTo(String value) {
            addCriterion("stage_update_time <>", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeGreaterThan(String value) {
            addCriterion("stage_update_time >", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("stage_update_time >=", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeLessThan(String value) {
            addCriterion("stage_update_time <", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("stage_update_time <=", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeLike(String value) {
            addCriterion("stage_update_time like", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeNotLike(String value) {
            addCriterion("stage_update_time not like", value, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeIn(List<String> values) {
            addCriterion("stage_update_time in", values, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeNotIn(List<String> values) {
            addCriterion("stage_update_time not in", values, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeBetween(String value1, String value2) {
            addCriterion("stage_update_time between", value1, value2, "stageUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStageUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("stage_update_time not between", value1, value2, "stageUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_datastage_view_input_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}