package com.bach.monitor.domain;

import java.util.Date;

public class BachDatastageJobList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.job_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.job_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String jobType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.job_category
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String jobCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.source_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.source_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.source_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sourceServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.source_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sourceUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.source_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sourcePwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.source_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sourceTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.source_query
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sourceQuery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.link_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String linkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.target_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.target_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String targetServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.target_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.target_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String targetUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.target_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String targetPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.target_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String targetTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.upsert
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String upsert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.write_mode
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String writeMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.before_sql
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String beforeSql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.after_sql
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String afterSql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.if_online
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String ifOnline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.src_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.src_tns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcTns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.src_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.src_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.src_tab_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcTabUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.src_tab_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcTabName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.src_where
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcWhere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.tgt_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tgtServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.tgt_tns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tgtTns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.tgt_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tgtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.tgt_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tgtPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.tgt_tab_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tgtTabUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.tgt_tab_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tgtTabName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.upsert2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String upsert2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.write_mode2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String writeMode2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_job_list.out_columns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String outColumns;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.job_name
     *
     * @return the value of bach_datastage_job_list.job_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.job_name
     *
     * @param jobName the value for bach_datastage_job_list.job_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.job_type
     *
     * @return the value of bach_datastage_job_list.job_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.job_type
     *
     * @param jobType the value for bach_datastage_job_list.job_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setJobType(String jobType) {
        this.jobType = jobType == null ? null : jobType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.job_category
     *
     * @return the value of bach_datastage_job_list.job_category
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getJobCategory() {
        return jobCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.job_category
     *
     * @param jobCategory the value for bach_datastage_job_list.job_category
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setJobCategory(String jobCategory) {
        this.jobCategory = jobCategory == null ? null : jobCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.source_name
     *
     * @return the value of bach_datastage_job_list.source_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.source_name
     *
     * @param sourceName the value for bach_datastage_job_list.source_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.source_type
     *
     * @return the value of bach_datastage_job_list.source_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.source_type
     *
     * @param sourceType the value for bach_datastage_job_list.source_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType == null ? null : sourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.source_server
     *
     * @return the value of bach_datastage_job_list.source_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSourceServer() {
        return sourceServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.source_server
     *
     * @param sourceServer the value for bach_datastage_job_list.source_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSourceServer(String sourceServer) {
        this.sourceServer = sourceServer == null ? null : sourceServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.source_user
     *
     * @return the value of bach_datastage_job_list.source_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSourceUser() {
        return sourceUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.source_user
     *
     * @param sourceUser the value for bach_datastage_job_list.source_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSourceUser(String sourceUser) {
        this.sourceUser = sourceUser == null ? null : sourceUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.source_pwd
     *
     * @return the value of bach_datastage_job_list.source_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSourcePwd() {
        return sourcePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.source_pwd
     *
     * @param sourcePwd the value for bach_datastage_job_list.source_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSourcePwd(String sourcePwd) {
        this.sourcePwd = sourcePwd == null ? null : sourcePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.source_table
     *
     * @return the value of bach_datastage_job_list.source_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSourceTable() {
        return sourceTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.source_table
     *
     * @param sourceTable the value for bach_datastage_job_list.source_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSourceTable(String sourceTable) {
        this.sourceTable = sourceTable == null ? null : sourceTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.source_query
     *
     * @return the value of bach_datastage_job_list.source_query
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSourceQuery() {
        return sourceQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.source_query
     *
     * @param sourceQuery the value for bach_datastage_job_list.source_query
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSourceQuery(String sourceQuery) {
        this.sourceQuery = sourceQuery == null ? null : sourceQuery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.link_type
     *
     * @return the value of bach_datastage_job_list.link_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.link_type
     *
     * @param linkType the value for bach_datastage_job_list.link_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setLinkType(String linkType) {
        this.linkType = linkType == null ? null : linkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.target_name
     *
     * @return the value of bach_datastage_job_list.target_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.target_name
     *
     * @param targetName the value for bach_datastage_job_list.target_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName == null ? null : targetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.target_server
     *
     * @return the value of bach_datastage_job_list.target_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTargetServer() {
        return targetServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.target_server
     *
     * @param targetServer the value for bach_datastage_job_list.target_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTargetServer(String targetServer) {
        this.targetServer = targetServer == null ? null : targetServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.target_type
     *
     * @return the value of bach_datastage_job_list.target_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.target_type
     *
     * @param targetType the value for bach_datastage_job_list.target_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.target_user
     *
     * @return the value of bach_datastage_job_list.target_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTargetUser() {
        return targetUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.target_user
     *
     * @param targetUser the value for bach_datastage_job_list.target_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTargetUser(String targetUser) {
        this.targetUser = targetUser == null ? null : targetUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.target_pwd
     *
     * @return the value of bach_datastage_job_list.target_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTargetPwd() {
        return targetPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.target_pwd
     *
     * @param targetPwd the value for bach_datastage_job_list.target_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTargetPwd(String targetPwd) {
        this.targetPwd = targetPwd == null ? null : targetPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.target_table
     *
     * @return the value of bach_datastage_job_list.target_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTargetTable() {
        return targetTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.target_table
     *
     * @param targetTable the value for bach_datastage_job_list.target_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTargetTable(String targetTable) {
        this.targetTable = targetTable == null ? null : targetTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.upsert
     *
     * @return the value of bach_datastage_job_list.upsert
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getUpsert() {
        return upsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.upsert
     *
     * @param upsert the value for bach_datastage_job_list.upsert
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUpsert(String upsert) {
        this.upsert = upsert == null ? null : upsert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.write_mode
     *
     * @return the value of bach_datastage_job_list.write_mode
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getWriteMode() {
        return writeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.write_mode
     *
     * @param writeMode the value for bach_datastage_job_list.write_mode
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setWriteMode(String writeMode) {
        this.writeMode = writeMode == null ? null : writeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.before_sql
     *
     * @return the value of bach_datastage_job_list.before_sql
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getBeforeSql() {
        return beforeSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.before_sql
     *
     * @param beforeSql the value for bach_datastage_job_list.before_sql
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setBeforeSql(String beforeSql) {
        this.beforeSql = beforeSql == null ? null : beforeSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.after_sql
     *
     * @return the value of bach_datastage_job_list.after_sql
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getAfterSql() {
        return afterSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.after_sql
     *
     * @param afterSql the value for bach_datastage_job_list.after_sql
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setAfterSql(String afterSql) {
        this.afterSql = afterSql == null ? null : afterSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.update_time
     *
     * @return the value of bach_datastage_job_list.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.update_time
     *
     * @param updateTime the value for bach_datastage_job_list.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.if_online
     *
     * @return the value of bach_datastage_job_list.if_online
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getIfOnline() {
        return ifOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.if_online
     *
     * @param ifOnline the value for bach_datastage_job_list.if_online
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setIfOnline(String ifOnline) {
        this.ifOnline = ifOnline == null ? null : ifOnline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.src_server
     *
     * @return the value of bach_datastage_job_list.src_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcServer() {
        return srcServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.src_server
     *
     * @param srcServer the value for bach_datastage_job_list.src_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcServer(String srcServer) {
        this.srcServer = srcServer == null ? null : srcServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.src_tns
     *
     * @return the value of bach_datastage_job_list.src_tns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcTns() {
        return srcTns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.src_tns
     *
     * @param srcTns the value for bach_datastage_job_list.src_tns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcTns(String srcTns) {
        this.srcTns = srcTns == null ? null : srcTns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.src_user
     *
     * @return the value of bach_datastage_job_list.src_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcUser() {
        return srcUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.src_user
     *
     * @param srcUser the value for bach_datastage_job_list.src_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcUser(String srcUser) {
        this.srcUser = srcUser == null ? null : srcUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.src_pwd
     *
     * @return the value of bach_datastage_job_list.src_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcPwd() {
        return srcPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.src_pwd
     *
     * @param srcPwd the value for bach_datastage_job_list.src_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcPwd(String srcPwd) {
        this.srcPwd = srcPwd == null ? null : srcPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.src_tab_user
     *
     * @return the value of bach_datastage_job_list.src_tab_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcTabUser() {
        return srcTabUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.src_tab_user
     *
     * @param srcTabUser the value for bach_datastage_job_list.src_tab_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcTabUser(String srcTabUser) {
        this.srcTabUser = srcTabUser == null ? null : srcTabUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.src_tab_name
     *
     * @return the value of bach_datastage_job_list.src_tab_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcTabName() {
        return srcTabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.src_tab_name
     *
     * @param srcTabName the value for bach_datastage_job_list.src_tab_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcTabName(String srcTabName) {
        this.srcTabName = srcTabName == null ? null : srcTabName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.src_where
     *
     * @return the value of bach_datastage_job_list.src_where
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcWhere() {
        return srcWhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.src_where
     *
     * @param srcWhere the value for bach_datastage_job_list.src_where
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcWhere(String srcWhere) {
        this.srcWhere = srcWhere == null ? null : srcWhere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.tgt_server
     *
     * @return the value of bach_datastage_job_list.tgt_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTgtServer() {
        return tgtServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.tgt_server
     *
     * @param tgtServer the value for bach_datastage_job_list.tgt_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTgtServer(String tgtServer) {
        this.tgtServer = tgtServer == null ? null : tgtServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.tgt_tns
     *
     * @return the value of bach_datastage_job_list.tgt_tns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTgtTns() {
        return tgtTns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.tgt_tns
     *
     * @param tgtTns the value for bach_datastage_job_list.tgt_tns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTgtTns(String tgtTns) {
        this.tgtTns = tgtTns == null ? null : tgtTns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.tgt_user
     *
     * @return the value of bach_datastage_job_list.tgt_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTgtUser() {
        return tgtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.tgt_user
     *
     * @param tgtUser the value for bach_datastage_job_list.tgt_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTgtUser(String tgtUser) {
        this.tgtUser = tgtUser == null ? null : tgtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.tgt_pwd
     *
     * @return the value of bach_datastage_job_list.tgt_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTgtPwd() {
        return tgtPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.tgt_pwd
     *
     * @param tgtPwd the value for bach_datastage_job_list.tgt_pwd
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTgtPwd(String tgtPwd) {
        this.tgtPwd = tgtPwd == null ? null : tgtPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.tgt_tab_user
     *
     * @return the value of bach_datastage_job_list.tgt_tab_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTgtTabUser() {
        return tgtTabUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.tgt_tab_user
     *
     * @param tgtTabUser the value for bach_datastage_job_list.tgt_tab_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTgtTabUser(String tgtTabUser) {
        this.tgtTabUser = tgtTabUser == null ? null : tgtTabUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.tgt_tab_name
     *
     * @return the value of bach_datastage_job_list.tgt_tab_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTgtTabName() {
        return tgtTabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.tgt_tab_name
     *
     * @param tgtTabName the value for bach_datastage_job_list.tgt_tab_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTgtTabName(String tgtTabName) {
        this.tgtTabName = tgtTabName == null ? null : tgtTabName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.upsert2
     *
     * @return the value of bach_datastage_job_list.upsert2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getUpsert2() {
        return upsert2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.upsert2
     *
     * @param upsert2 the value for bach_datastage_job_list.upsert2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUpsert2(String upsert2) {
        this.upsert2 = upsert2 == null ? null : upsert2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.write_mode2
     *
     * @return the value of bach_datastage_job_list.write_mode2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getWriteMode2() {
        return writeMode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.write_mode2
     *
     * @param writeMode2 the value for bach_datastage_job_list.write_mode2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setWriteMode2(String writeMode2) {
        this.writeMode2 = writeMode2 == null ? null : writeMode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_job_list.out_columns
     *
     * @return the value of bach_datastage_job_list.out_columns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOutColumns() {
        return outColumns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_job_list.out_columns
     *
     * @param outColumns the value for bach_datastage_job_list.out_columns
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOutColumns(String outColumns) {
        this.outColumns = outColumns == null ? null : outColumns.trim();
    }
}