package com.bach.monitor.domain;

public class BachDatastageParamUser2WithBLOBs extends BachDatastageParamUser2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user2.sqlplus
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String sqlplus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user2.tns_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tnsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user2.c_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String cUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user2.c_password
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String cPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user2.c_password2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String cPassword2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user2.sqlplus
     *
     * @return the value of bach_datastage_param_user2.sqlplus
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSqlplus() {
        return sqlplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user2.sqlplus
     *
     * @param sqlplus the value for bach_datastage_param_user2.sqlplus
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSqlplus(String sqlplus) {
        this.sqlplus = sqlplus == null ? null : sqlplus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user2.tns_name
     *
     * @return the value of bach_datastage_param_user2.tns_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTnsName() {
        return tnsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user2.tns_name
     *
     * @param tnsName the value for bach_datastage_param_user2.tns_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTnsName(String tnsName) {
        this.tnsName = tnsName == null ? null : tnsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user2.c_user
     *
     * @return the value of bach_datastage_param_user2.c_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getcUser() {
        return cUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user2.c_user
     *
     * @param cUser the value for bach_datastage_param_user2.c_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setcUser(String cUser) {
        this.cUser = cUser == null ? null : cUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user2.c_password
     *
     * @return the value of bach_datastage_param_user2.c_password
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getcPassword() {
        return cPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user2.c_password
     *
     * @param cPassword the value for bach_datastage_param_user2.c_password
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setcPassword(String cPassword) {
        this.cPassword = cPassword == null ? null : cPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user2.c_password2
     *
     * @return the value of bach_datastage_param_user2.c_password2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getcPassword2() {
        return cPassword2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user2.c_password2
     *
     * @param cPassword2 the value for bach_datastage_param_user2.c_password2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setcPassword2(String cPassword2) {
        this.cPassword2 = cPassword2 == null ? null : cPassword2.trim();
    }
}