package com.bach.monitor.domain;

public class BachOggSourceTableInfo20181113 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_source_table_info_20181113.ip
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_source_table_info_20181113.src_table_owner
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcTableOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_source_table_info_20181113.src_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String srcTableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_source_table_info_20181113.ip
     *
     * @return the value of bach_ogg_source_table_info_20181113.ip
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_source_table_info_20181113.ip
     *
     * @param ip the value for bach_ogg_source_table_info_20181113.ip
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_source_table_info_20181113.src_table_owner
     *
     * @return the value of bach_ogg_source_table_info_20181113.src_table_owner
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcTableOwner() {
        return srcTableOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_source_table_info_20181113.src_table_owner
     *
     * @param srcTableOwner the value for bach_ogg_source_table_info_20181113.src_table_owner
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcTableOwner(String srcTableOwner) {
        this.srcTableOwner = srcTableOwner == null ? null : srcTableOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_source_table_info_20181113.src_table_name
     *
     * @return the value of bach_ogg_source_table_info_20181113.src_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getSrcTableName() {
        return srcTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_source_table_info_20181113.src_table_name
     *
     * @param srcTableName the value for bach_ogg_source_table_info_20181113.src_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setSrcTableName(String srcTableName) {
        this.srcTableName = srcTableName == null ? null : srcTableName.trim();
    }
}