package com.bach.monitor.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BachAlarmtypeDbExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public BachAlarmtypeDbExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAlarmNumIsNull() {
            addCriterion("ALARM_NUM is null");
            return (Criteria) this;
        }

        public Criteria andAlarmNumIsNotNull() {
            addCriterion("ALARM_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmNumEqualTo(Integer value) {
            addCriterion("ALARM_NUM =", value, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumNotEqualTo(Integer value) {
            addCriterion("ALARM_NUM <>", value, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumGreaterThan(Integer value) {
            addCriterion("ALARM_NUM >", value, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ALARM_NUM >=", value, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumLessThan(Integer value) {
            addCriterion("ALARM_NUM <", value, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumLessThanOrEqualTo(Integer value) {
            addCriterion("ALARM_NUM <=", value, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumIn(List<Integer> values) {
            addCriterion("ALARM_NUM in", values, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumNotIn(List<Integer> values) {
            addCriterion("ALARM_NUM not in", values, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumBetween(Integer value1, Integer value2) {
            addCriterion("ALARM_NUM between", value1, value2, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andAlarmNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ALARM_NUM not between", value1, value2, "alarmNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumIsNull() {
            addCriterion("MONITOR_NUM is null");
            return (Criteria) this;
        }

        public Criteria andMonitorNumIsNotNull() {
            addCriterion("MONITOR_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorNumEqualTo(Integer value) {
            addCriterion("MONITOR_NUM =", value, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumNotEqualTo(Integer value) {
            addCriterion("MONITOR_NUM <>", value, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumGreaterThan(Integer value) {
            addCriterion("MONITOR_NUM >", value, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("MONITOR_NUM >=", value, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumLessThan(Integer value) {
            addCriterion("MONITOR_NUM <", value, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumLessThanOrEqualTo(Integer value) {
            addCriterion("MONITOR_NUM <=", value, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumIn(List<Integer> values) {
            addCriterion("MONITOR_NUM in", values, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumNotIn(List<Integer> values) {
            addCriterion("MONITOR_NUM not in", values, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumBetween(Integer value1, Integer value2) {
            addCriterion("MONITOR_NUM between", value1, value2, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andMonitorNumNotBetween(Integer value1, Integer value2) {
            addCriterion("MONITOR_NUM not between", value1, value2, "monitorNum");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeIsNull() {
            addCriterion("ALARM_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeIsNotNull() {
            addCriterion("ALARM_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeEqualTo(String value) {
            addCriterion("ALARM_TYPE =", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotEqualTo(String value) {
            addCriterion("ALARM_TYPE <>", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeGreaterThan(String value) {
            addCriterion("ALARM_TYPE >", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ALARM_TYPE >=", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeLessThan(String value) {
            addCriterion("ALARM_TYPE <", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeLessThanOrEqualTo(String value) {
            addCriterion("ALARM_TYPE <=", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeLike(String value) {
            addCriterion("ALARM_TYPE like", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotLike(String value) {
            addCriterion("ALARM_TYPE not like", value, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeIn(List<String> values) {
            addCriterion("ALARM_TYPE in", values, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotIn(List<String> values) {
            addCriterion("ALARM_TYPE not in", values, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeBetween(String value1, String value2) {
            addCriterion("ALARM_TYPE between", value1, value2, "alarmType");
            return (Criteria) this;
        }

        public Criteria andAlarmTypeNotBetween(String value1, String value2) {
            addCriterion("ALARM_TYPE not between", value1, value2, "alarmType");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNull() {
            addCriterion("SERVER_IP is null");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNotNull() {
            addCriterion("SERVER_IP is not null");
            return (Criteria) this;
        }

        public Criteria andServerIpEqualTo(String value) {
            addCriterion("SERVER_IP =", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotEqualTo(String value) {
            addCriterion("SERVER_IP <>", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThan(String value) {
            addCriterion("SERVER_IP >", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("SERVER_IP >=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThan(String value) {
            addCriterion("SERVER_IP <", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThanOrEqualTo(String value) {
            addCriterion("SERVER_IP <=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLike(String value) {
            addCriterion("SERVER_IP like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotLike(String value) {
            addCriterion("SERVER_IP not like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpIn(List<String> values) {
            addCriterion("SERVER_IP in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotIn(List<String> values) {
            addCriterion("SERVER_IP not in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpBetween(String value1, String value2) {
            addCriterion("SERVER_IP between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotBetween(String value1, String value2) {
            addCriterion("SERVER_IP not between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andAlarmNameIsNull() {
            addCriterion("ALARM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAlarmNameIsNotNull() {
            addCriterion("ALARM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmNameEqualTo(String value) {
            addCriterion("ALARM_NAME =", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameNotEqualTo(String value) {
            addCriterion("ALARM_NAME <>", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameGreaterThan(String value) {
            addCriterion("ALARM_NAME >", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameGreaterThanOrEqualTo(String value) {
            addCriterion("ALARM_NAME >=", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameLessThan(String value) {
            addCriterion("ALARM_NAME <", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameLessThanOrEqualTo(String value) {
            addCriterion("ALARM_NAME <=", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameLike(String value) {
            addCriterion("ALARM_NAME like", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameNotLike(String value) {
            addCriterion("ALARM_NAME not like", value, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameIn(List<String> values) {
            addCriterion("ALARM_NAME in", values, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameNotIn(List<String> values) {
            addCriterion("ALARM_NAME not in", values, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameBetween(String value1, String value2) {
            addCriterion("ALARM_NAME between", value1, value2, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmNameNotBetween(String value1, String value2) {
            addCriterion("ALARM_NAME not between", value1, value2, "alarmName");
            return (Criteria) this;
        }

        public Criteria andAlarmContentIsNull() {
            addCriterion("ALARM_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andAlarmContentIsNotNull() {
            addCriterion("ALARM_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmContentEqualTo(String value) {
            addCriterion("ALARM_CONTENT =", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotEqualTo(String value) {
            addCriterion("ALARM_CONTENT <>", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentGreaterThan(String value) {
            addCriterion("ALARM_CONTENT >", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentGreaterThanOrEqualTo(String value) {
            addCriterion("ALARM_CONTENT >=", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentLessThan(String value) {
            addCriterion("ALARM_CONTENT <", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentLessThanOrEqualTo(String value) {
            addCriterion("ALARM_CONTENT <=", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentLike(String value) {
            addCriterion("ALARM_CONTENT like", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotLike(String value) {
            addCriterion("ALARM_CONTENT not like", value, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentIn(List<String> values) {
            addCriterion("ALARM_CONTENT in", values, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotIn(List<String> values) {
            addCriterion("ALARM_CONTENT not in", values, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentBetween(String value1, String value2) {
            addCriterion("ALARM_CONTENT between", value1, value2, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmContentNotBetween(String value1, String value2) {
            addCriterion("ALARM_CONTENT not between", value1, value2, "alarmContent");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeIsNull() {
            addCriterion("ALARM_PROTIME is null");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeIsNotNull() {
            addCriterion("ALARM_PROTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeEqualTo(Date value) {
            addCriterion("ALARM_PROTIME =", value, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeNotEqualTo(Date value) {
            addCriterion("ALARM_PROTIME <>", value, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeGreaterThan(Date value) {
            addCriterion("ALARM_PROTIME >", value, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ALARM_PROTIME >=", value, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeLessThan(Date value) {
            addCriterion("ALARM_PROTIME <", value, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeLessThanOrEqualTo(Date value) {
            addCriterion("ALARM_PROTIME <=", value, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeIn(List<Date> values) {
            addCriterion("ALARM_PROTIME in", values, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeNotIn(List<Date> values) {
            addCriterion("ALARM_PROTIME not in", values, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeBetween(Date value1, Date value2) {
            addCriterion("ALARM_PROTIME between", value1, value2, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andAlarmProtimeNotBetween(Date value1, Date value2) {
            addCriterion("ALARM_PROTIME not between", value1, value2, "alarmProtime");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("VALID is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("VALID is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Boolean value) {
            addCriterion("VALID =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Boolean value) {
            addCriterion("VALID <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Boolean value) {
            addCriterion("VALID >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("VALID >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Boolean value) {
            addCriterion("VALID <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Boolean value) {
            addCriterion("VALID <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Boolean> values) {
            addCriterion("VALID in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Boolean> values) {
            addCriterion("VALID not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Boolean value1, Boolean value2) {
            addCriterion("VALID between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("VALID not between", value1, value2, "valid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_alarmtype_db
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}