package com.bach.monitor.domain;

import java.util.ArrayList;
import java.util.List;

public class BachOggUploadInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public BachOggUploadInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOggIpIsNull() {
            addCriterion("ogg_ip is null");
            return (Criteria) this;
        }

        public Criteria andOggIpIsNotNull() {
            addCriterion("ogg_ip is not null");
            return (Criteria) this;
        }

        public Criteria andOggIpEqualTo(String value) {
            addCriterion("ogg_ip =", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpNotEqualTo(String value) {
            addCriterion("ogg_ip <>", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpGreaterThan(String value) {
            addCriterion("ogg_ip >", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpGreaterThanOrEqualTo(String value) {
            addCriterion("ogg_ip >=", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpLessThan(String value) {
            addCriterion("ogg_ip <", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpLessThanOrEqualTo(String value) {
            addCriterion("ogg_ip <=", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpLike(String value) {
            addCriterion("ogg_ip like", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpNotLike(String value) {
            addCriterion("ogg_ip not like", value, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpIn(List<String> values) {
            addCriterion("ogg_ip in", values, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpNotIn(List<String> values) {
            addCriterion("ogg_ip not in", values, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpBetween(String value1, String value2) {
            addCriterion("ogg_ip between", value1, value2, "oggIp");
            return (Criteria) this;
        }

        public Criteria andOggIpNotBetween(String value1, String value2) {
            addCriterion("ogg_ip not between", value1, value2, "oggIp");
            return (Criteria) this;
        }

        public Criteria andLocalFileIsNull() {
            addCriterion("local_file is null");
            return (Criteria) this;
        }

        public Criteria andLocalFileIsNotNull() {
            addCriterion("local_file is not null");
            return (Criteria) this;
        }

        public Criteria andLocalFileEqualTo(String value) {
            addCriterion("local_file =", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileNotEqualTo(String value) {
            addCriterion("local_file <>", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileGreaterThan(String value) {
            addCriterion("local_file >", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileGreaterThanOrEqualTo(String value) {
            addCriterion("local_file >=", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileLessThan(String value) {
            addCriterion("local_file <", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileLessThanOrEqualTo(String value) {
            addCriterion("local_file <=", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileLike(String value) {
            addCriterion("local_file like", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileNotLike(String value) {
            addCriterion("local_file not like", value, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileIn(List<String> values) {
            addCriterion("local_file in", values, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileNotIn(List<String> values) {
            addCriterion("local_file not in", values, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileBetween(String value1, String value2) {
            addCriterion("local_file between", value1, value2, "localFile");
            return (Criteria) this;
        }

        public Criteria andLocalFileNotBetween(String value1, String value2) {
            addCriterion("local_file not between", value1, value2, "localFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileIsNull() {
            addCriterion("remote_file is null");
            return (Criteria) this;
        }

        public Criteria andRemoteFileIsNotNull() {
            addCriterion("remote_file is not null");
            return (Criteria) this;
        }

        public Criteria andRemoteFileEqualTo(String value) {
            addCriterion("remote_file =", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileNotEqualTo(String value) {
            addCriterion("remote_file <>", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileGreaterThan(String value) {
            addCriterion("remote_file >", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileGreaterThanOrEqualTo(String value) {
            addCriterion("remote_file >=", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileLessThan(String value) {
            addCriterion("remote_file <", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileLessThanOrEqualTo(String value) {
            addCriterion("remote_file <=", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileLike(String value) {
            addCriterion("remote_file like", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileNotLike(String value) {
            addCriterion("remote_file not like", value, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileIn(List<String> values) {
            addCriterion("remote_file in", values, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileNotIn(List<String> values) {
            addCriterion("remote_file not in", values, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileBetween(String value1, String value2) {
            addCriterion("remote_file between", value1, value2, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteFileNotBetween(String value1, String value2) {
            addCriterion("remote_file not between", value1, value2, "remoteFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileIsNull() {
            addCriterion("remote_bak_file is null");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileIsNotNull() {
            addCriterion("remote_bak_file is not null");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileEqualTo(String value) {
            addCriterion("remote_bak_file =", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileNotEqualTo(String value) {
            addCriterion("remote_bak_file <>", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileGreaterThan(String value) {
            addCriterion("remote_bak_file >", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileGreaterThanOrEqualTo(String value) {
            addCriterion("remote_bak_file >=", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileLessThan(String value) {
            addCriterion("remote_bak_file <", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileLessThanOrEqualTo(String value) {
            addCriterion("remote_bak_file <=", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileLike(String value) {
            addCriterion("remote_bak_file like", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileNotLike(String value) {
            addCriterion("remote_bak_file not like", value, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileIn(List<String> values) {
            addCriterion("remote_bak_file in", values, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileNotIn(List<String> values) {
            addCriterion("remote_bak_file not in", values, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileBetween(String value1, String value2) {
            addCriterion("remote_bak_file between", value1, value2, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andRemoteBakFileNotBetween(String value1, String value2) {
            addCriterion("remote_bak_file not between", value1, value2, "remoteBakFile");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeIsNull() {
            addCriterion("back_file_size is null");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeIsNotNull() {
            addCriterion("back_file_size is not null");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeEqualTo(String value) {
            addCriterion("back_file_size =", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeNotEqualTo(String value) {
            addCriterion("back_file_size <>", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeGreaterThan(String value) {
            addCriterion("back_file_size >", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeGreaterThanOrEqualTo(String value) {
            addCriterion("back_file_size >=", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeLessThan(String value) {
            addCriterion("back_file_size <", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeLessThanOrEqualTo(String value) {
            addCriterion("back_file_size <=", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeLike(String value) {
            addCriterion("back_file_size like", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeNotLike(String value) {
            addCriterion("back_file_size not like", value, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeIn(List<String> values) {
            addCriterion("back_file_size in", values, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeNotIn(List<String> values) {
            addCriterion("back_file_size not in", values, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeBetween(String value1, String value2) {
            addCriterion("back_file_size between", value1, value2, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileSizeNotBetween(String value1, String value2) {
            addCriterion("back_file_size not between", value1, value2, "backFileSize");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5IsNull() {
            addCriterion("back_file_md5 is null");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5IsNotNull() {
            addCriterion("back_file_md5 is not null");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5EqualTo(String value) {
            addCriterion("back_file_md5 =", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5NotEqualTo(String value) {
            addCriterion("back_file_md5 <>", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5GreaterThan(String value) {
            addCriterion("back_file_md5 >", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5GreaterThanOrEqualTo(String value) {
            addCriterion("back_file_md5 >=", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5LessThan(String value) {
            addCriterion("back_file_md5 <", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5LessThanOrEqualTo(String value) {
            addCriterion("back_file_md5 <=", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5Like(String value) {
            addCriterion("back_file_md5 like", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5NotLike(String value) {
            addCriterion("back_file_md5 not like", value, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5In(List<String> values) {
            addCriterion("back_file_md5 in", values, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5NotIn(List<String> values) {
            addCriterion("back_file_md5 not in", values, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5Between(String value1, String value2) {
            addCriterion("back_file_md5 between", value1, value2, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andBackFileMd5NotBetween(String value1, String value2) {
            addCriterion("back_file_md5 not between", value1, value2, "backFileMd5");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("channel_name =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("channel_name <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("channel_name like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("channel_name not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("channel_name in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andBakTypeIsNull() {
            addCriterion("bak_type is null");
            return (Criteria) this;
        }

        public Criteria andBakTypeIsNotNull() {
            addCriterion("bak_type is not null");
            return (Criteria) this;
        }

        public Criteria andBakTypeEqualTo(String value) {
            addCriterion("bak_type =", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeNotEqualTo(String value) {
            addCriterion("bak_type <>", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeGreaterThan(String value) {
            addCriterion("bak_type >", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bak_type >=", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeLessThan(String value) {
            addCriterion("bak_type <", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeLessThanOrEqualTo(String value) {
            addCriterion("bak_type <=", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeLike(String value) {
            addCriterion("bak_type like", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeNotLike(String value) {
            addCriterion("bak_type not like", value, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeIn(List<String> values) {
            addCriterion("bak_type in", values, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeNotIn(List<String> values) {
            addCriterion("bak_type not in", values, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeBetween(String value1, String value2) {
            addCriterion("bak_type between", value1, value2, "bakType");
            return (Criteria) this;
        }

        public Criteria andBakTypeNotBetween(String value1, String value2) {
            addCriterion("bak_type not between", value1, value2, "bakType");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_ogg_upload_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}