package com.bach.monitor.domain;

public class BachOggExtractChannelInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_extract_channel_info.ip
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_extract_channel_info.channel_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String channelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_extract_channel_info.channel
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_extract_channel_info.trail_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String trailName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_ogg_extract_channel_info.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_extract_channel_info.ip
     *
     * @return the value of bach_ogg_extract_channel_info.ip
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_extract_channel_info.ip
     *
     * @param ip the value for bach_ogg_extract_channel_info.ip
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_extract_channel_info.channel_type
     *
     * @return the value of bach_ogg_extract_channel_info.channel_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_extract_channel_info.channel_type
     *
     * @param channelType the value for bach_ogg_extract_channel_info.channel_type
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_extract_channel_info.channel
     *
     * @return the value of bach_ogg_extract_channel_info.channel
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_extract_channel_info.channel
     *
     * @param channel the value for bach_ogg_extract_channel_info.channel
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_extract_channel_info.trail_name
     *
     * @return the value of bach_ogg_extract_channel_info.trail_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTrailName() {
        return trailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_extract_channel_info.trail_name
     *
     * @param trailName the value for bach_ogg_extract_channel_info.trail_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTrailName(String trailName) {
        this.trailName = trailName == null ? null : trailName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_ogg_extract_channel_info.update_time
     *
     * @return the value of bach_ogg_extract_channel_info.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_ogg_extract_channel_info.update_time
     *
     * @param updateTime the value for bach_ogg_extract_channel_info.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}