package com.bach.monitor.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BachDatastageJobStatusHisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public BachDatastageJobStatusHisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobNameIsNull() {
            addCriterion("job_name is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("job_name =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("job_name <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("job_name >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("job_name >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("job_name <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("job_name <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("job_name like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("job_name not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("job_name in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("job_name not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("job_name between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("job_name not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andIfOnlineIsNull() {
            addCriterion("if_online is null");
            return (Criteria) this;
        }

        public Criteria andIfOnlineIsNotNull() {
            addCriterion("if_online is not null");
            return (Criteria) this;
        }

        public Criteria andIfOnlineEqualTo(String value) {
            addCriterion("if_online =", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotEqualTo(String value) {
            addCriterion("if_online <>", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineGreaterThan(String value) {
            addCriterion("if_online >", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineGreaterThanOrEqualTo(String value) {
            addCriterion("if_online >=", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineLessThan(String value) {
            addCriterion("if_online <", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineLessThanOrEqualTo(String value) {
            addCriterion("if_online <=", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineLike(String value) {
            addCriterion("if_online like", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotLike(String value) {
            addCriterion("if_online not like", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineIn(List<String> values) {
            addCriterion("if_online in", values, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotIn(List<String> values) {
            addCriterion("if_online not in", values, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineBetween(String value1, String value2) {
            addCriterion("if_online between", value1, value2, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotBetween(String value1, String value2) {
            addCriterion("if_online not between", value1, value2, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeIsNull() {
            addCriterion("elapsed_time is null");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeIsNotNull() {
            addCriterion("elapsed_time is not null");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeEqualTo(Integer value) {
            addCriterion("elapsed_time =", value, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeNotEqualTo(Integer value) {
            addCriterion("elapsed_time <>", value, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeGreaterThan(Integer value) {
            addCriterion("elapsed_time >", value, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("elapsed_time >=", value, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeLessThan(Integer value) {
            addCriterion("elapsed_time <", value, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeLessThanOrEqualTo(Integer value) {
            addCriterion("elapsed_time <=", value, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeIn(List<Integer> values) {
            addCriterion("elapsed_time in", values, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeNotIn(List<Integer> values) {
            addCriterion("elapsed_time not in", values, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeBetween(Integer value1, Integer value2) {
            addCriterion("elapsed_time between", value1, value2, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andElapsedTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("elapsed_time not between", value1, value2, "elapsedTime");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNull() {
            addCriterion("job_status is null");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNotNull() {
            addCriterion("job_status is not null");
            return (Criteria) this;
        }

        public Criteria andJobStatusEqualTo(String value) {
            addCriterion("job_status =", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotEqualTo(String value) {
            addCriterion("job_status <>", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThan(String value) {
            addCriterion("job_status >", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThanOrEqualTo(String value) {
            addCriterion("job_status >=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThan(String value) {
            addCriterion("job_status <", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThanOrEqualTo(String value) {
            addCriterion("job_status <=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLike(String value) {
            addCriterion("job_status like", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotLike(String value) {
            addCriterion("job_status not like", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusIn(List<String> values) {
            addCriterion("job_status in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotIn(List<String> values) {
            addCriterion("job_status not in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusBetween(String value1, String value2) {
            addCriterion("job_status between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotBetween(String value1, String value2) {
            addCriterion("job_status not between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeIsNull() {
            addCriterion("avg_elapsed_time is null");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeIsNotNull() {
            addCriterion("avg_elapsed_time is not null");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeEqualTo(Integer value) {
            addCriterion("avg_elapsed_time =", value, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeNotEqualTo(Integer value) {
            addCriterion("avg_elapsed_time <>", value, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeGreaterThan(Integer value) {
            addCriterion("avg_elapsed_time >", value, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("avg_elapsed_time >=", value, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeLessThan(Integer value) {
            addCriterion("avg_elapsed_time <", value, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeLessThanOrEqualTo(Integer value) {
            addCriterion("avg_elapsed_time <=", value, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeIn(List<Integer> values) {
            addCriterion("avg_elapsed_time in", values, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeNotIn(List<Integer> values) {
            addCriterion("avg_elapsed_time not in", values, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeBetween(Integer value1, Integer value2) {
            addCriterion("avg_elapsed_time between", value1, value2, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andAvgElapsedTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("avg_elapsed_time not between", value1, value2, "avgElapsedTime");
            return (Criteria) this;
        }

        public Criteria andParentJobNameIsNull() {
            addCriterion("parent_job_name is null");
            return (Criteria) this;
        }

        public Criteria andParentJobNameIsNotNull() {
            addCriterion("parent_job_name is not null");
            return (Criteria) this;
        }

        public Criteria andParentJobNameEqualTo(String value) {
            addCriterion("parent_job_name =", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameNotEqualTo(String value) {
            addCriterion("parent_job_name <>", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameGreaterThan(String value) {
            addCriterion("parent_job_name >", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("parent_job_name >=", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameLessThan(String value) {
            addCriterion("parent_job_name <", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameLessThanOrEqualTo(String value) {
            addCriterion("parent_job_name <=", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameLike(String value) {
            addCriterion("parent_job_name like", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameNotLike(String value) {
            addCriterion("parent_job_name not like", value, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameIn(List<String> values) {
            addCriterion("parent_job_name in", values, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameNotIn(List<String> values) {
            addCriterion("parent_job_name not in", values, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameBetween(String value1, String value2) {
            addCriterion("parent_job_name between", value1, value2, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andParentJobNameNotBetween(String value1, String value2) {
            addCriterion("parent_job_name not between", value1, value2, "parentJobName");
            return (Criteria) this;
        }

        public Criteria andSeqNameIsNull() {
            addCriterion("seq_name is null");
            return (Criteria) this;
        }

        public Criteria andSeqNameIsNotNull() {
            addCriterion("seq_name is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNameEqualTo(String value) {
            addCriterion("seq_name =", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotEqualTo(String value) {
            addCriterion("seq_name <>", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameGreaterThan(String value) {
            addCriterion("seq_name >", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameGreaterThanOrEqualTo(String value) {
            addCriterion("seq_name >=", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameLessThan(String value) {
            addCriterion("seq_name <", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameLessThanOrEqualTo(String value) {
            addCriterion("seq_name <=", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameLike(String value) {
            addCriterion("seq_name like", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotLike(String value) {
            addCriterion("seq_name not like", value, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameIn(List<String> values) {
            addCriterion("seq_name in", values, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotIn(List<String> values) {
            addCriterion("seq_name not in", values, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameBetween(String value1, String value2) {
            addCriterion("seq_name between", value1, value2, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqNameNotBetween(String value1, String value2) {
            addCriterion("seq_name not between", value1, value2, "seqName");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryIsNull() {
            addCriterion("seq_category is null");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryIsNotNull() {
            addCriterion("seq_category is not null");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryEqualTo(String value) {
            addCriterion("seq_category =", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryNotEqualTo(String value) {
            addCriterion("seq_category <>", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryGreaterThan(String value) {
            addCriterion("seq_category >", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("seq_category >=", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryLessThan(String value) {
            addCriterion("seq_category <", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryLessThanOrEqualTo(String value) {
            addCriterion("seq_category <=", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryLike(String value) {
            addCriterion("seq_category like", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryNotLike(String value) {
            addCriterion("seq_category not like", value, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryIn(List<String> values) {
            addCriterion("seq_category in", values, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryNotIn(List<String> values) {
            addCriterion("seq_category not in", values, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryBetween(String value1, String value2) {
            addCriterion("seq_category between", value1, value2, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqCategoryNotBetween(String value1, String value2) {
            addCriterion("seq_category not between", value1, value2, "seqCategory");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeIsNull() {
            addCriterion("seq_update_time is null");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeIsNotNull() {
            addCriterion("seq_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeEqualTo(Date value) {
            addCriterion("seq_update_time =", value, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeNotEqualTo(Date value) {
            addCriterion("seq_update_time <>", value, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeGreaterThan(Date value) {
            addCriterion("seq_update_time >", value, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("seq_update_time >=", value, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeLessThan(Date value) {
            addCriterion("seq_update_time <", value, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("seq_update_time <=", value, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeIn(List<Date> values) {
            addCriterion("seq_update_time in", values, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeNotIn(List<Date> values) {
            addCriterion("seq_update_time not in", values, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("seq_update_time between", value1, value2, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSeqUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("seq_update_time not between", value1, value2, "seqUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNull() {
            addCriterion("reg_time is null");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNotNull() {
            addCriterion("reg_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegTimeEqualTo(Date value) {
            addCriterion("reg_time =", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotEqualTo(Date value) {
            addCriterion("reg_time <>", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThan(Date value) {
            addCriterion("reg_time >", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("reg_time >=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThan(Date value) {
            addCriterion("reg_time <", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThanOrEqualTo(Date value) {
            addCriterion("reg_time <=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeIn(List<Date> values) {
            addCriterion("reg_time in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotIn(List<Date> values) {
            addCriterion("reg_time not in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeBetween(Date value1, Date value2) {
            addCriterion("reg_time between", value1, value2, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotBetween(Date value1, Date value2) {
            addCriterion("reg_time not between", value1, value2, "regTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_datastage_job_status_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}