package com.bach.monitor.domain;

public class BachAlarmPermissionRoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_alarm_permission_role.role_id
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_alarm_permission_role.monitor_num
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private Integer monitorNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_alarm_permission_role.employee_num
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String employeeNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_alarm_permission_role.role_id
     *
     * @return the value of bach_alarm_permission_role.role_id
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_alarm_permission_role.role_id
     *
     * @param roleId the value for bach_alarm_permission_role.role_id
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_alarm_permission_role.monitor_num
     *
     * @return the value of bach_alarm_permission_role.monitor_num
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Integer getMonitorNum() {
        return monitorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_alarm_permission_role.monitor_num
     *
     * @param monitorNum the value for bach_alarm_permission_role.monitor_num
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setMonitorNum(Integer monitorNum) {
        this.monitorNum = monitorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_alarm_permission_role.employee_num
     *
     * @return the value of bach_alarm_permission_role.employee_num
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getEmployeeNum() {
        return employeeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_alarm_permission_role.employee_num
     *
     * @param employeeNum the value for bach_alarm_permission_role.employee_num
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setEmployeeNum(String employeeNum) {
        this.employeeNum = employeeNum == null ? null : employeeNum.trim();
    }
}