package com.bach.monitor.domain;

public class BachDatastageTableDefinitions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_table_definitions.identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_table_definitions.modified_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_table_definitions.data_store
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String dataStore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_table_definitions.data_schema
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String dataSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_table_definitions.data_collection
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String dataCollection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_table_definitions.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_table_definitions.identifier
     *
     * @return the value of bach_datastage_table_definitions.identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_table_definitions.identifier
     *
     * @param identifier the value for bach_datastage_table_definitions.identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_table_definitions.modified_time
     *
     * @return the value of bach_datastage_table_definitions.modified_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_table_definitions.modified_time
     *
     * @param modifiedTime the value for bach_datastage_table_definitions.modified_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setModifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime == null ? null : modifiedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_table_definitions.data_store
     *
     * @return the value of bach_datastage_table_definitions.data_store
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getDataStore() {
        return dataStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_table_definitions.data_store
     *
     * @param dataStore the value for bach_datastage_table_definitions.data_store
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDataStore(String dataStore) {
        this.dataStore = dataStore == null ? null : dataStore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_table_definitions.data_schema
     *
     * @return the value of bach_datastage_table_definitions.data_schema
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getDataSchema() {
        return dataSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_table_definitions.data_schema
     *
     * @param dataSchema the value for bach_datastage_table_definitions.data_schema
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDataSchema(String dataSchema) {
        this.dataSchema = dataSchema == null ? null : dataSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_table_definitions.data_collection
     *
     * @return the value of bach_datastage_table_definitions.data_collection
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getDataCollection() {
        return dataCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_table_definitions.data_collection
     *
     * @param dataCollection the value for bach_datastage_table_definitions.data_collection
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDataCollection(String dataCollection) {
        this.dataCollection = dataCollection == null ? null : dataCollection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_table_definitions.update_time
     *
     * @return the value of bach_datastage_table_definitions.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_table_definitions.update_time
     *
     * @param updateTime the value for bach_datastage_table_definitions.update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}