package com.bach.monitor.domain;

public class BachDatastageViewInputTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.collect_server_suffix
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String collectServerSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.dboptions_user_suffix
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String dboptionsUserSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.query_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String queryTableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.collection_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String collectionTableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.output_job_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String outputJobIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.output_record_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String outputRecordIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.output_update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String outputUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.stage_job_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String stageJobIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.bstage_record_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String bstageRecordIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_view_input_table.stage_update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String stageUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.collect_server_suffix
     *
     * @return the value of bach_datastage_view_input_table.collect_server_suffix
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getCollectServerSuffix() {
        return collectServerSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.collect_server_suffix
     *
     * @param collectServerSuffix the value for bach_datastage_view_input_table.collect_server_suffix
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setCollectServerSuffix(String collectServerSuffix) {
        this.collectServerSuffix = collectServerSuffix == null ? null : collectServerSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.dboptions_user_suffix
     *
     * @return the value of bach_datastage_view_input_table.dboptions_user_suffix
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getDboptionsUserSuffix() {
        return dboptionsUserSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.dboptions_user_suffix
     *
     * @param dboptionsUserSuffix the value for bach_datastage_view_input_table.dboptions_user_suffix
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDboptionsUserSuffix(String dboptionsUserSuffix) {
        this.dboptionsUserSuffix = dboptionsUserSuffix == null ? null : dboptionsUserSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.query_table_name
     *
     * @return the value of bach_datastage_view_input_table.query_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getQueryTableName() {
        return queryTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.query_table_name
     *
     * @param queryTableName the value for bach_datastage_view_input_table.query_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setQueryTableName(String queryTableName) {
        this.queryTableName = queryTableName == null ? null : queryTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.collection_table_name
     *
     * @return the value of bach_datastage_view_input_table.collection_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getCollectionTableName() {
        return collectionTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.collection_table_name
     *
     * @param collectionTableName the value for bach_datastage_view_input_table.collection_table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setCollectionTableName(String collectionTableName) {
        this.collectionTableName = collectionTableName == null ? null : collectionTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.table_name
     *
     * @return the value of bach_datastage_view_input_table.table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.table_name
     *
     * @param tableName the value for bach_datastage_view_input_table.table_name
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.output_job_identifier
     *
     * @return the value of bach_datastage_view_input_table.output_job_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOutputJobIdentifier() {
        return outputJobIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.output_job_identifier
     *
     * @param outputJobIdentifier the value for bach_datastage_view_input_table.output_job_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOutputJobIdentifier(String outputJobIdentifier) {
        this.outputJobIdentifier = outputJobIdentifier == null ? null : outputJobIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.output_record_identifier
     *
     * @return the value of bach_datastage_view_input_table.output_record_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOutputRecordIdentifier() {
        return outputRecordIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.output_record_identifier
     *
     * @param outputRecordIdentifier the value for bach_datastage_view_input_table.output_record_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOutputRecordIdentifier(String outputRecordIdentifier) {
        this.outputRecordIdentifier = outputRecordIdentifier == null ? null : outputRecordIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.output_update_time
     *
     * @return the value of bach_datastage_view_input_table.output_update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOutputUpdateTime() {
        return outputUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.output_update_time
     *
     * @param outputUpdateTime the value for bach_datastage_view_input_table.output_update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOutputUpdateTime(String outputUpdateTime) {
        this.outputUpdateTime = outputUpdateTime == null ? null : outputUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.stage_job_identifier
     *
     * @return the value of bach_datastage_view_input_table.stage_job_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getStageJobIdentifier() {
        return stageJobIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.stage_job_identifier
     *
     * @param stageJobIdentifier the value for bach_datastage_view_input_table.stage_job_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setStageJobIdentifier(String stageJobIdentifier) {
        this.stageJobIdentifier = stageJobIdentifier == null ? null : stageJobIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.bstage_record_identifier
     *
     * @return the value of bach_datastage_view_input_table.bstage_record_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getBstageRecordIdentifier() {
        return bstageRecordIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.bstage_record_identifier
     *
     * @param bstageRecordIdentifier the value for bach_datastage_view_input_table.bstage_record_identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setBstageRecordIdentifier(String bstageRecordIdentifier) {
        this.bstageRecordIdentifier = bstageRecordIdentifier == null ? null : bstageRecordIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_view_input_table.stage_update_time
     *
     * @return the value of bach_datastage_view_input_table.stage_update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getStageUpdateTime() {
        return stageUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_view_input_table.stage_update_time
     *
     * @param stageUpdateTime the value for bach_datastage_view_input_table.stage_update_time
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setStageUpdateTime(String stageUpdateTime) {
        this.stageUpdateTime = stageUpdateTime == null ? null : stageUpdateTime.trim();
    }
}