package com.bach.monitor.domain;

import java.util.ArrayList;
import java.util.List;

public class BachOggChannelMapSrcViewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public BachOggChannelMapSrcViewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("channel like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("channel not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelTypeIsNull() {
            addCriterion("channel_type is null");
            return (Criteria) this;
        }

        public Criteria andChannelTypeIsNotNull() {
            addCriterion("channel_type is not null");
            return (Criteria) this;
        }

        public Criteria andChannelTypeEqualTo(String value) {
            addCriterion("channel_type =", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotEqualTo(String value) {
            addCriterion("channel_type <>", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeGreaterThan(String value) {
            addCriterion("channel_type >", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("channel_type >=", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeLessThan(String value) {
            addCriterion("channel_type <", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeLessThanOrEqualTo(String value) {
            addCriterion("channel_type <=", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeLike(String value) {
            addCriterion("channel_type like", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotLike(String value) {
            addCriterion("channel_type not like", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeIn(List<String> values) {
            addCriterion("channel_type in", values, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotIn(List<String> values) {
            addCriterion("channel_type not in", values, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeBetween(String value1, String value2) {
            addCriterion("channel_type between", value1, value2, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotBetween(String value1, String value2) {
            addCriterion("channel_type not between", value1, value2, "channelType");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointIsNull() {
            addCriterion("read_check_point is null");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointIsNotNull() {
            addCriterion("read_check_point is not null");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointEqualTo(String value) {
            addCriterion("read_check_point =", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointNotEqualTo(String value) {
            addCriterion("read_check_point <>", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointGreaterThan(String value) {
            addCriterion("read_check_point >", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointGreaterThanOrEqualTo(String value) {
            addCriterion("read_check_point >=", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointLessThan(String value) {
            addCriterion("read_check_point <", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointLessThanOrEqualTo(String value) {
            addCriterion("read_check_point <=", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointLike(String value) {
            addCriterion("read_check_point like", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointNotLike(String value) {
            addCriterion("read_check_point not like", value, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointIn(List<String> values) {
            addCriterion("read_check_point in", values, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointNotIn(List<String> values) {
            addCriterion("read_check_point not in", values, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointBetween(String value1, String value2) {
            addCriterion("read_check_point between", value1, value2, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointNotBetween(String value1, String value2) {
            addCriterion("read_check_point not between", value1, value2, "readCheckPoint");
            return (Criteria) this;
        }

        public Criteria andTrailNameIsNull() {
            addCriterion("trail_name is null");
            return (Criteria) this;
        }

        public Criteria andTrailNameIsNotNull() {
            addCriterion("trail_name is not null");
            return (Criteria) this;
        }

        public Criteria andTrailNameEqualTo(String value) {
            addCriterion("trail_name =", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameNotEqualTo(String value) {
            addCriterion("trail_name <>", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameGreaterThan(String value) {
            addCriterion("trail_name >", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameGreaterThanOrEqualTo(String value) {
            addCriterion("trail_name >=", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameLessThan(String value) {
            addCriterion("trail_name <", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameLessThanOrEqualTo(String value) {
            addCriterion("trail_name <=", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameLike(String value) {
            addCriterion("trail_name like", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameNotLike(String value) {
            addCriterion("trail_name not like", value, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameIn(List<String> values) {
            addCriterion("trail_name in", values, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameNotIn(List<String> values) {
            addCriterion("trail_name not in", values, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameBetween(String value1, String value2) {
            addCriterion("trail_name between", value1, value2, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailNameNotBetween(String value1, String value2) {
            addCriterion("trail_name not between", value1, value2, "trailName");
            return (Criteria) this;
        }

        public Criteria andTrailKeyIsNull() {
            addCriterion("trail_key is null");
            return (Criteria) this;
        }

        public Criteria andTrailKeyIsNotNull() {
            addCriterion("trail_key is not null");
            return (Criteria) this;
        }

        public Criteria andTrailKeyEqualTo(String value) {
            addCriterion("trail_key =", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyNotEqualTo(String value) {
            addCriterion("trail_key <>", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyGreaterThan(String value) {
            addCriterion("trail_key >", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyGreaterThanOrEqualTo(String value) {
            addCriterion("trail_key >=", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyLessThan(String value) {
            addCriterion("trail_key <", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyLessThanOrEqualTo(String value) {
            addCriterion("trail_key <=", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyLike(String value) {
            addCriterion("trail_key like", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyNotLike(String value) {
            addCriterion("trail_key not like", value, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyIn(List<String> values) {
            addCriterion("trail_key in", values, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyNotIn(List<String> values) {
            addCriterion("trail_key not in", values, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyBetween(String value1, String value2) {
            addCriterion("trail_key between", value1, value2, "trailKey");
            return (Criteria) this;
        }

        public Criteria andTrailKeyNotBetween(String value1, String value2) {
            addCriterion("trail_key not between", value1, value2, "trailKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyIsNull() {
            addCriterion("read_check_point_key is null");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyIsNotNull() {
            addCriterion("read_check_point_key is not null");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyEqualTo(String value) {
            addCriterion("read_check_point_key =", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyNotEqualTo(String value) {
            addCriterion("read_check_point_key <>", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyGreaterThan(String value) {
            addCriterion("read_check_point_key >", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyGreaterThanOrEqualTo(String value) {
            addCriterion("read_check_point_key >=", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyLessThan(String value) {
            addCriterion("read_check_point_key <", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyLessThanOrEqualTo(String value) {
            addCriterion("read_check_point_key <=", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyLike(String value) {
            addCriterion("read_check_point_key like", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyNotLike(String value) {
            addCriterion("read_check_point_key not like", value, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyIn(List<String> values) {
            addCriterion("read_check_point_key in", values, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyNotIn(List<String> values) {
            addCriterion("read_check_point_key not in", values, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyBetween(String value1, String value2) {
            addCriterion("read_check_point_key between", value1, value2, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andReadCheckPointKeyNotBetween(String value1, String value2) {
            addCriterion("read_check_point_key not between", value1, value2, "readCheckPointKey");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBIpIsNull() {
            addCriterion("b_ip is null");
            return (Criteria) this;
        }

        public Criteria andBIpIsNotNull() {
            addCriterion("b_ip is not null");
            return (Criteria) this;
        }

        public Criteria andBIpEqualTo(String value) {
            addCriterion("b_ip =", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpNotEqualTo(String value) {
            addCriterion("b_ip <>", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpGreaterThan(String value) {
            addCriterion("b_ip >", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpGreaterThanOrEqualTo(String value) {
            addCriterion("b_ip >=", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpLessThan(String value) {
            addCriterion("b_ip <", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpLessThanOrEqualTo(String value) {
            addCriterion("b_ip <=", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpLike(String value) {
            addCriterion("b_ip like", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpNotLike(String value) {
            addCriterion("b_ip not like", value, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpIn(List<String> values) {
            addCriterion("b_ip in", values, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpNotIn(List<String> values) {
            addCriterion("b_ip not in", values, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpBetween(String value1, String value2) {
            addCriterion("b_ip between", value1, value2, "bIp");
            return (Criteria) this;
        }

        public Criteria andBIpNotBetween(String value1, String value2) {
            addCriterion("b_ip not between", value1, value2, "bIp");
            return (Criteria) this;
        }

        public Criteria andBChannelIsNull() {
            addCriterion("b_channel is null");
            return (Criteria) this;
        }

        public Criteria andBChannelIsNotNull() {
            addCriterion("b_channel is not null");
            return (Criteria) this;
        }

        public Criteria andBChannelEqualTo(String value) {
            addCriterion("b_channel =", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelNotEqualTo(String value) {
            addCriterion("b_channel <>", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelGreaterThan(String value) {
            addCriterion("b_channel >", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelGreaterThanOrEqualTo(String value) {
            addCriterion("b_channel >=", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelLessThan(String value) {
            addCriterion("b_channel <", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelLessThanOrEqualTo(String value) {
            addCriterion("b_channel <=", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelLike(String value) {
            addCriterion("b_channel like", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelNotLike(String value) {
            addCriterion("b_channel not like", value, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelIn(List<String> values) {
            addCriterion("b_channel in", values, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelNotIn(List<String> values) {
            addCriterion("b_channel not in", values, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelBetween(String value1, String value2) {
            addCriterion("b_channel between", value1, value2, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelNotBetween(String value1, String value2) {
            addCriterion("b_channel not between", value1, value2, "bChannel");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeIsNull() {
            addCriterion("b_channel_type is null");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeIsNotNull() {
            addCriterion("b_channel_type is not null");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeEqualTo(String value) {
            addCriterion("b_channel_type =", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeNotEqualTo(String value) {
            addCriterion("b_channel_type <>", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeGreaterThan(String value) {
            addCriterion("b_channel_type >", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("b_channel_type >=", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeLessThan(String value) {
            addCriterion("b_channel_type <", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeLessThanOrEqualTo(String value) {
            addCriterion("b_channel_type <=", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeLike(String value) {
            addCriterion("b_channel_type like", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeNotLike(String value) {
            addCriterion("b_channel_type not like", value, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeIn(List<String> values) {
            addCriterion("b_channel_type in", values, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeNotIn(List<String> values) {
            addCriterion("b_channel_type not in", values, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeBetween(String value1, String value2) {
            addCriterion("b_channel_type between", value1, value2, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBChannelTypeNotBetween(String value1, String value2) {
            addCriterion("b_channel_type not between", value1, value2, "bChannelType");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyIsNull() {
            addCriterion("b_trail_key is null");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyIsNotNull() {
            addCriterion("b_trail_key is not null");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyEqualTo(String value) {
            addCriterion("b_trail_key =", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyNotEqualTo(String value) {
            addCriterion("b_trail_key <>", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyGreaterThan(String value) {
            addCriterion("b_trail_key >", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyGreaterThanOrEqualTo(String value) {
            addCriterion("b_trail_key >=", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyLessThan(String value) {
            addCriterion("b_trail_key <", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyLessThanOrEqualTo(String value) {
            addCriterion("b_trail_key <=", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyLike(String value) {
            addCriterion("b_trail_key like", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyNotLike(String value) {
            addCriterion("b_trail_key not like", value, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyIn(List<String> values) {
            addCriterion("b_trail_key in", values, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyNotIn(List<String> values) {
            addCriterion("b_trail_key not in", values, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyBetween(String value1, String value2) {
            addCriterion("b_trail_key between", value1, value2, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andBTrailKeyNotBetween(String value1, String value2) {
            addCriterion("b_trail_key not between", value1, value2, "bTrailKey");
            return (Criteria) this;
        }

        public Criteria andRipIsNull() {
            addCriterion("rip is null");
            return (Criteria) this;
        }

        public Criteria andRipIsNotNull() {
            addCriterion("rip is not null");
            return (Criteria) this;
        }

        public Criteria andRipEqualTo(String value) {
            addCriterion("rip =", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipNotEqualTo(String value) {
            addCriterion("rip <>", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipGreaterThan(String value) {
            addCriterion("rip >", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipGreaterThanOrEqualTo(String value) {
            addCriterion("rip >=", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipLessThan(String value) {
            addCriterion("rip <", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipLessThanOrEqualTo(String value) {
            addCriterion("rip <=", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipLike(String value) {
            addCriterion("rip like", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipNotLike(String value) {
            addCriterion("rip not like", value, "rip");
            return (Criteria) this;
        }

        public Criteria andRipIn(List<String> values) {
            addCriterion("rip in", values, "rip");
            return (Criteria) this;
        }

        public Criteria andRipNotIn(List<String> values) {
            addCriterion("rip not in", values, "rip");
            return (Criteria) this;
        }

        public Criteria andRipBetween(String value1, String value2) {
            addCriterion("rip between", value1, value2, "rip");
            return (Criteria) this;
        }

        public Criteria andRipNotBetween(String value1, String value2) {
            addCriterion("rip not between", value1, value2, "rip");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bach_ogg_channel_map_src_view
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}