package com.bach.monitor.domain;

public class BachDatastageParamUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user.identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user.prop1
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String prop1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bach_datastage_param_user.prop2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    private String prop2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user.identifier
     *
     * @return the value of bach_datastage_param_user.identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user.identifier
     *
     * @param identifier the value for bach_datastage_param_user.identifier
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user.prop1
     *
     * @return the value of bach_datastage_param_user.prop1
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getProp1() {
        return prop1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user.prop1
     *
     * @param prop1 the value for bach_datastage_param_user.prop1
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setProp1(String prop1) {
        this.prop1 = prop1 == null ? null : prop1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bach_datastage_param_user.prop2
     *
     * @return the value of bach_datastage_param_user.prop2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public String getProp2() {
        return prop2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bach_datastage_param_user.prop2
     *
     * @param prop2 the value for bach_datastage_param_user.prop2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    public void setProp2(String prop2) {
        this.prop2 = prop2 == null ? null : prop2.trim();
    }
}