package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmtypeApplication;
import com.bach.monitor.domain.BachAlarmtypeApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmtypeApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmtypeApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmtypeApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmtypeApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmtypeApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmtypeApplication> selectByExampleWithBLOBs(BachAlarmtypeApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmtypeApplication> selectByExample(BachAlarmtypeApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmtypeApplication selectByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmtypeApplication record, @Param("example") BachAlarmtypeApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachAlarmtypeApplication record, @Param("example") BachAlarmtypeApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmtypeApplication record, @Param("example") BachAlarmtypeApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmtypeApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(BachAlarmtypeApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_application
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmtypeApplication record);
}