package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageRowsLogHis;
import com.bach.monitor.domain.BachDatastageRowsLogHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageRowsLogHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_rows_log_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageRowsLogHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_rows_log_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageRowsLogHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_rows_log_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageRowsLogHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_rows_log_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageRowsLogHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_rows_log_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageRowsLogHis> selectByExample(BachDatastageRowsLogHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_rows_log_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageRowsLogHis record, @Param("example") BachDatastageRowsLogHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_rows_log_his
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageRowsLogHis record, @Param("example") BachDatastageRowsLogHisExample example);
}