package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageJobCustomInput;
import com.bach.monitor.domain.BachDatastageJobCustomInputExample;
import com.bach.monitor.domain.BachDatastageJobCustomInputWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageJobCustomInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageJobCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageJobCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageJobCustomInputWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageJobCustomInputWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageJobCustomInputWithBLOBs> selectByExampleWithBLOBs(BachDatastageJobCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageJobCustomInput> selectByExample(BachDatastageJobCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageJobCustomInputWithBLOBs record, @Param("example") BachDatastageJobCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachDatastageJobCustomInputWithBLOBs record, @Param("example") BachDatastageJobCustomInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_input
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageJobCustomInput record, @Param("example") BachDatastageJobCustomInputExample example);
}