package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmUserRole;
import com.bach.monitor.domain.BachAlarmUserRoleExample;
import com.bach.monitor.domain.BachAlarmUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(BachAlarmUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmUserRole> selectByExample(BachAlarmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmUserRole selectByPrimaryKey(BachAlarmUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmUserRole record, @Param("example") BachAlarmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmUserRole record, @Param("example") BachAlarmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmUserRole record);
}