package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageTaskStatus;
import com.bach.monitor.domain.BachDatastageTaskStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageTaskStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_task_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageTaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_task_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageTaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_task_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageTaskStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_task_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageTaskStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_task_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageTaskStatus> selectByExample(BachDatastageTaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_task_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageTaskStatus record, @Param("example") BachDatastageTaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_task_status
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageTaskStatus record, @Param("example") BachDatastageTaskStatusExample example);
}