package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageCrontabInfo;
import com.bach.monitor.domain.BachDatastageCrontabInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageCrontabInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageCrontabInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageCrontabInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageCrontabInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageCrontabInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageCrontabInfo> selectByExampleWithBLOBs(BachDatastageCrontabInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageCrontabInfo> selectByExample(BachDatastageCrontabInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageCrontabInfo record, @Param("example") BachDatastageCrontabInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachDatastageCrontabInfo record, @Param("example") BachDatastageCrontabInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_crontab_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageCrontabInfo record, @Param("example") BachDatastageCrontabInfoExample example);
}