package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmtypeProcessingLogic;
import com.bach.monitor.domain.BachAlarmtypeProcessingLogicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmtypeProcessingLogicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmtypeProcessingLogicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmtypeProcessingLogicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmtypeProcessingLogic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmtypeProcessingLogic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmtypeProcessingLogic> selectByExampleWithBLOBs(BachAlarmtypeProcessingLogicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmtypeProcessingLogic> selectByExample(BachAlarmtypeProcessingLogicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmtypeProcessingLogic selectByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmtypeProcessingLogic record, @Param("example") BachAlarmtypeProcessingLogicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachAlarmtypeProcessingLogic record, @Param("example") BachAlarmtypeProcessingLogicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmtypeProcessingLogic record, @Param("example") BachAlarmtypeProcessingLogicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmtypeProcessingLogic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(BachAlarmtypeProcessingLogic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_processing_logic
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmtypeProcessingLogic record);
}