package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmtypeJob;
import com.bach.monitor.domain.BachAlarmtypeJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmtypeJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmtypeJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmtypeJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmtypeJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmtypeJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmtypeJob> selectByExampleWithBLOBs(BachAlarmtypeJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmtypeJob> selectByExample(BachAlarmtypeJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmtypeJob selectByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmtypeJob record, @Param("example") BachAlarmtypeJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachAlarmtypeJob record, @Param("example") BachAlarmtypeJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmtypeJob record, @Param("example") BachAlarmtypeJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmtypeJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(BachAlarmtypeJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarmtype_job
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmtypeJob record);
}