package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageItilSjtbList;
import com.bach.monitor.domain.BachDatastageItilSjtbListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageItilSjtbListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageItilSjtbListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageItilSjtbListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(String flowno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageItilSjtbList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageItilSjtbList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageItilSjtbList> selectByExample(BachDatastageItilSjtbListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachDatastageItilSjtbList selectByPrimaryKey(String flowno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageItilSjtbList record, @Param("example") BachDatastageItilSjtbListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageItilSjtbList record, @Param("example") BachDatastageItilSjtbListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachDatastageItilSjtbList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_itil_sjtb_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachDatastageItilSjtbList record);
}