package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachOggPmpChannelParameter;
import com.bach.monitor.domain.BachOggPmpChannelParameterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachOggPmpChannelParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_pmp_channel_parameter
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachOggPmpChannelParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_pmp_channel_parameter
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachOggPmpChannelParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_pmp_channel_parameter
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachOggPmpChannelParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_pmp_channel_parameter
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachOggPmpChannelParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_pmp_channel_parameter
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachOggPmpChannelParameter> selectByExample(BachOggPmpChannelParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_pmp_channel_parameter
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachOggPmpChannelParameter record, @Param("example") BachOggPmpChannelParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_pmp_channel_parameter
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachOggPmpChannelParameter record, @Param("example") BachOggPmpChannelParameterExample example);
}