package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmPermission;
import com.bach.monitor.domain.BachAlarmPermissionExample;
import com.bach.monitor.domain.BachAlarmPermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(BachAlarmPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmPermission> selectByExample(BachAlarmPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmPermission selectByPrimaryKey(BachAlarmPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmPermission record, @Param("example") BachAlarmPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmPermission record, @Param("example") BachAlarmPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmPermission record);
}