package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageJobCustomStage;
import com.bach.monitor.domain.BachDatastageJobCustomStageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageJobCustomStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageJobCustomStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageJobCustomStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageJobCustomStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageJobCustomStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageJobCustomStage> selectByExampleWithBLOBs(BachDatastageJobCustomStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageJobCustomStage> selectByExample(BachDatastageJobCustomStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageJobCustomStage record, @Param("example") BachDatastageJobCustomStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachDatastageJobCustomStage record, @Param("example") BachDatastageJobCustomStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_custom_stage
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageJobCustomStage record, @Param("example") BachDatastageJobCustomStageExample example);
}