package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachOggSourceTableInfo20181113;
import com.bach.monitor.domain.BachOggSourceTableInfo20181113Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachOggSourceTableInfo20181113Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_20181113
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachOggSourceTableInfo20181113Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_20181113
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachOggSourceTableInfo20181113Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_20181113
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachOggSourceTableInfo20181113 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_20181113
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachOggSourceTableInfo20181113 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_20181113
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachOggSourceTableInfo20181113> selectByExample(BachOggSourceTableInfo20181113Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_20181113
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachOggSourceTableInfo20181113 record, @Param("example") BachOggSourceTableInfo20181113Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_20181113
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachOggSourceTableInfo20181113 record, @Param("example") BachOggSourceTableInfo20181113Example example);
}