package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageJobListSys;
import com.bach.monitor.domain.BachDatastageJobListSysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageJobListSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_list_sys
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageJobListSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_list_sys
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageJobListSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_list_sys
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageJobListSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_list_sys
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageJobListSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_list_sys
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageJobListSys> selectByExample(BachDatastageJobListSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_list_sys
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageJobListSys record, @Param("example") BachDatastageJobListSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_list_sys
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageJobListSys record, @Param("example") BachDatastageJobListSysExample example);
}