package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachOggSourceTableInfo18;
import com.bach.monitor.domain.BachOggSourceTableInfo18Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachOggSourceTableInfo18Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_18
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachOggSourceTableInfo18Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_18
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachOggSourceTableInfo18Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_18
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachOggSourceTableInfo18 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_18
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachOggSourceTableInfo18 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_18
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachOggSourceTableInfo18> selectByExample(BachOggSourceTableInfo18Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_18
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachOggSourceTableInfo18 record, @Param("example") BachOggSourceTableInfo18Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_source_table_info_18
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachOggSourceTableInfo18 record, @Param("example") BachOggSourceTableInfo18Example example);
}