package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageJobDestTable;
import com.bach.monitor.domain.BachDatastageJobDestTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageJobDestTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_dest_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageJobDestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_dest_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageJobDestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_dest_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageJobDestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_dest_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageJobDestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_dest_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageJobDestTable> selectByExample(BachDatastageJobDestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_dest_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageJobDestTable record, @Param("example") BachDatastageJobDestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_job_dest_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageJobDestTable record, @Param("example") BachDatastageJobDestTableExample example);
}