package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageTableDefinitions;
import com.bach.monitor.domain.BachDatastageTableDefinitionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageTableDefinitionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_table_definitions
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageTableDefinitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_table_definitions
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageTableDefinitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_table_definitions
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageTableDefinitions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_table_definitions
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageTableDefinitions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_table_definitions
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageTableDefinitions> selectByExample(BachDatastageTableDefinitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_table_definitions
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageTableDefinitions record, @Param("example") BachDatastageTableDefinitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_table_definitions
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageTableDefinitions record, @Param("example") BachDatastageTableDefinitionsExample example);
}