package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachOggDestTableInfo;
import com.bach.monitor.domain.BachOggDestTableInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachOggDestTableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_dest_table_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachOggDestTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_dest_table_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachOggDestTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_dest_table_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachOggDestTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_dest_table_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachOggDestTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_dest_table_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachOggDestTableInfo> selectByExample(BachOggDestTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_dest_table_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachOggDestTableInfo record, @Param("example") BachOggDestTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_dest_table_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachOggDestTableInfo record, @Param("example") BachOggDestTableInfoExample example);
}