package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmPermissionRole;
import com.bach.monitor.domain.BachAlarmPermissionRoleExample;
import com.bach.monitor.domain.BachAlarmPermissionRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmPermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(BachAlarmPermissionRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmPermissionRole> selectByExample(BachAlarmPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmPermissionRole selectByPrimaryKey(BachAlarmPermissionRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmPermissionRole record, @Param("example") BachAlarmPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmPermissionRole record, @Param("example") BachAlarmPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_permission_role
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmPermissionRole record);
}