package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmSubtype;
import com.bach.monitor.domain.BachAlarmSubtypeExample;
import com.bach.monitor.domain.BachAlarmSubtypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmSubtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmSubtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmSubtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(BachAlarmSubtypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmSubtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmSubtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmSubtype> selectByExample(BachAlarmSubtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmSubtype selectByPrimaryKey(BachAlarmSubtypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmSubtype record, @Param("example") BachAlarmSubtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmSubtype record, @Param("example") BachAlarmSubtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmSubtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_subtype
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmSubtype record);
}