package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachOggExtractChannelInfo;
import com.bach.monitor.domain.BachOggExtractChannelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachOggExtractChannelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_extract_channel_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachOggExtractChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_extract_channel_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachOggExtractChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_extract_channel_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachOggExtractChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_extract_channel_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachOggExtractChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_extract_channel_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachOggExtractChannelInfo> selectByExample(BachOggExtractChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_extract_channel_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachOggExtractChannelInfo record, @Param("example") BachOggExtractChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_ogg_extract_channel_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachOggExtractChannelInfo record, @Param("example") BachOggExtractChannelInfoExample example);
}