package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageSyncList;
import com.bach.monitor.domain.BachDatastageSyncListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageSyncListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_sync_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageSyncListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_sync_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageSyncListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_sync_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageSyncList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_sync_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageSyncList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_sync_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageSyncList> selectByExample(BachDatastageSyncListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_sync_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageSyncList record, @Param("example") BachDatastageSyncListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_sync_list
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageSyncList record, @Param("example") BachDatastageSyncListExample example);
}