package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageParameters;
import com.bach.monitor.domain.BachDatastageParametersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageParametersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageParameters> selectByExampleWithBLOBs(BachDatastageParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageParameters> selectByExample(BachDatastageParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageParameters record, @Param("example") BachDatastageParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachDatastageParameters record, @Param("example") BachDatastageParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_parameters
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageParameters record, @Param("example") BachDatastageParametersExample example);
}