package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageParamUser2;
import com.bach.monitor.domain.BachDatastageParamUser2Example;
import com.bach.monitor.domain.BachDatastageParamUser2WithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageParamUser2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageParamUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageParamUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageParamUser2WithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageParamUser2WithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageParamUser2WithBLOBs> selectByExampleWithBLOBs(BachDatastageParamUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageParamUser2> selectByExample(BachDatastageParamUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageParamUser2WithBLOBs record, @Param("example") BachDatastageParamUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachDatastageParamUser2WithBLOBs record, @Param("example") BachDatastageParamUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_user2
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageParamUser2 record, @Param("example") BachDatastageParamUser2Example example);
}