package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageDestinationTable;
import com.bach.monitor.domain.BachDatastageDestinationTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageDestinationTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_destination_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageDestinationTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_destination_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageDestinationTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_destination_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageDestinationTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_destination_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageDestinationTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_destination_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageDestinationTable> selectByExample(BachDatastageDestinationTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_destination_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageDestinationTable record, @Param("example") BachDatastageDestinationTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_destination_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageDestinationTable record, @Param("example") BachDatastageDestinationTableExample example);
}