package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachAlarmUser;
import com.bach.monitor.domain.BachAlarmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachAlarmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachAlarmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachAlarmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachAlarmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachAlarmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachAlarmUser> selectByExample(BachAlarmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachAlarmUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachAlarmUser record, @Param("example") BachAlarmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachAlarmUser record, @Param("example") BachAlarmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachAlarmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_alarm_user
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachAlarmUser record);
}