package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachOldAlarmNotification;
import com.bach.monitor.domain.BachOldAlarmNotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachOldAlarmNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachOldAlarmNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachOldAlarmNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachOldAlarmNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachOldAlarmNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachOldAlarmNotification> selectByExample(BachOldAlarmNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachOldAlarmNotification selectByPrimaryKey(Integer alarmNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachOldAlarmNotification record, @Param("example") BachOldAlarmNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachOldAlarmNotification record, @Param("example") BachOldAlarmNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachOldAlarmNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_old_alarm_notification
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachOldAlarmNotification record);
}