package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageParamServer;
import com.bach.monitor.domain.BachDatastageParamServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageParamServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageParamServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageParamServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageParamServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageParamServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageParamServer> selectByExampleWithBLOBs(BachDatastageParamServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageParamServer> selectByExample(BachDatastageParamServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageParamServer record, @Param("example") BachDatastageParamServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BachDatastageParamServer record, @Param("example") BachDatastageParamServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_param_server
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageParamServer record, @Param("example") BachDatastageParamServerExample example);
}