package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachServerUserInfo;
import com.bach.monitor.domain.BachServerUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachServerUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachServerUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachServerUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachServerUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachServerUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachServerUserInfo> selectByExample(BachServerUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    BachServerUserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachServerUserInfo record, @Param("example") BachServerUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachServerUserInfo record, @Param("example") BachServerUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(BachServerUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_server_user_info
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByPrimaryKey(BachServerUserInfo record);
}