package com.bach.monitor.mapper;

import com.bach.monitor.domain.BachDatastageOriginalTable;
import com.bach.monitor.domain.BachDatastageOriginalTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BachDatastageOriginalTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_original_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    long countByExample(BachDatastageOriginalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_original_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int deleteByExample(BachDatastageOriginalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_original_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insert(BachDatastageOriginalTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_original_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int insertSelective(BachDatastageOriginalTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_original_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    List<BachDatastageOriginalTable> selectByExample(BachDatastageOriginalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_original_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") BachDatastageOriginalTable record, @Param("example") BachDatastageOriginalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bach_datastage_original_table
     *
     * @mbg.generated Thu Aug 01 12:36:06 CST 2019
     */
    int updateByExample(@Param("record") BachDatastageOriginalTable record, @Param("example") BachDatastageOriginalTableExample example);
}